<?php
/** @var Silex\Application $app */

$app['translator.domains'] = [
    'messages' => [
        'ru' => array(
            'more' => 'Подробнее',
            'register' => 'Зарегистрироваться',
            'login' => 'Войти',
            'invitation_to_registration' => ' А Вы знаете, что зарегистрированным пользователям доступна масса полезных функций?<br/>',
            'benefits_of_registration' => '- Возможность добавлять толкования; <br/>- Закладывать закладки в нужных
        местах Писания;<br/>- Оставлять заметки на Библейские стихи;<br/>- Выделять маркером избранные стихи;<br/>-
        Читать Библию по одному из выбранных планов чтения.<br/><br/>',
            'appeal_to_donate' => 'Понравился сайт?<br /> Пожалуйста, <a href="http://fond.predanie.ru/blago/340442/" target="_blank">пожертвуйте</a> на развитие и содержание!',
            'yesterday' => 'Вчера',
            'today' => 'Сегодня',
            'tomorrow' => 'Завтра',
            'year_abbr' => 'г.',
            'not_found' => 'Страница не найдена',
            'news' => 'Новости',
            'author' => 'Автор',
            'written_when' => 'Время написания',
            'written_where' => 'Место написания',
            'total_chapters' => 'В книге глав',
            'total_verses' => 'и всего стихов',
            'verses' => 'стихов',
            'chapter' => 'глава',
            'audio_tag_is_not_supported' => 'Тег audio не поддерживается вашим браузером.',
            'audio' => 'Аудио',
            'about_book' => 'СВЕДЕНИЯ О КНИГЕ',
            'page_is_NOT_found' => 'Страница не существует',
            'sorry_PAGE_is_not_found' => 'Извините, но такая страница на нашем сайте отсутствует,<br />либо Вы ввели неверные данные :-(',
            'notes' => 'Примечания',
            'source' => 'Источник',
            'other_commentary' => 'Иное толкование',
            'about_exeget' => 'Информация об экзегете',
            'lived_when' => 'Период жизни',
            'century' => 'век',
            'belongs' => 'Принадлежность',
            'all_commentaries' => 'Все толкования экзегета',
            'commentaries' => 'Толкования',
            'researches' => 'Исследования',
            'info' => 'Информация',
            'next_chapter' => 'Следующая глава',
            'prev_chapter' => 'Предыдущая глава',
            'parallel_verses' => 'Параллельные стихи',
            'parallel_verses_not_found' => 'Параллельные стихи отсутствуют!',
            'exegets' => 'Экзегеты',
            'all_exegets' => 'Екзегеты, чьи толкования представлены на нашем сайте',
            'total_commentaries' => 'Всего найдено толкований',
            'admin_title' => 'Раздел редактирования и администрирования',
            'lang' => 'язык/language'
        ),
    ],
];